---
- name: Converge
  hosts: all
  vars:
    selinux_reboot: false
  pre_tasks:
    - name: update cache for debian systems
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - guidugli.selinux
